# Generated by Django 5.0.6 on 2024-07-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.TextField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
